---
title: "ICOTS-10 Notes"
output: pdf_document
---

## Front Matter

#### Terms

- *Cognitive transfer* has been used in the learning literature to describe the degree to which knowledge can be successfully applied to new or novel situations (e.g., Singley & Anderson, 1989)

- Introductory Statistics Understanding and Discernment Outcomes (ISTUDIO) Assessment


#### Goals for the session

0. Introduce ISTUDIO Assessment
1. What was ISTUDIO designed to measure? 
2. One slide outline of the study
3. **What we learn when asking questions like this?**



## What was ISTUDIO designed to measure?

*Chris Wild said in his talk on Tuesday, that our courses should emphasize students doing the stuff that **can't** be automated... honestly, that's a pretty good summary of what ISTUDIO attempts to measure*


#### Slide Text 

1. Discernment of statistical questions
    - **Reflexively asking and answering "Can statistics help?" is perhaps the first step to productive analysis**
    - Difference between deterministic and stochastic inquiry (Franklin & Garfield, 2006)

2. Statistical thinking
    - Can students *cognitively* make their way between context of the task at hand and architypical "models" abstracted from experience and prior encounters
    - **ISTUDIO attempts to isolate each direction in the shuttling process**
        - context to architype (some in L&C have called this "backward transfer")
        - architype to context (and this "forward transfer")


## BRIEF outline of study 

- Fairly large sample of post-secondary students across US
- Convenience Sample of instructors that replied to email solicitations
- 7 **open-ended** tasks, each with two or more parts
- (This part was shared with students)
    - Inference is appropriate for some, but **NOT ALL** questions.
    - Respond as though you are **giving advice/instructions to a classmate** that has asked you for help.
    - Enough detail that a classmate could **carry out your instructions**, and explain how he or she should **interpret the result**
    - **NO Calculations**
- Scoring
    - Curriculum agnostic--no calculations anyway, intentional rubric design
    - Every task has a detailed rubric with real student examplars
    - Rubric development and analysis available in Beckman (2015)
- Leaving psychometric analysis out of scope here, but reported in detail elsewhere

\newpage

## What do we learn when asking questions like this?

## Task Description: Note Identification task 

Item credit: Garfield, J., delMas, R., & Zieffler, A. (2012)


#### Key details

- Some people who have a good ear for music can identify the notes they hear when music is played.
- A music teacher choosing and playing a note at random on the piano.  
- The student names which note was played without looking.
- **Suppose you want to determine whether a student named Carla has a “good ear for music” using this method of note identification.**

#### Prompts

- Should statistical inference be used?  Explain. 

- Explain how you would decide whether Carla has a good ear for music using this method of note identification.  



## Selected responses to the Note Identification task

#. "Since statistical inferences measure population it would not be a good idea to use this in the case of carla because it is measuring the accuracy of her note identification skills, not measuring a population." (Student 1038)

#. "No, I don't think so because you are not comparing her data to anyone else's data or to an overall population." (Student 1006)

#. "No, because Carla is an individual in the population not a sample" (Student 780)

## Observation: Population as a process

- 35 of the 178 students ($\approx 20\%$) said that statistical inference was **NOT** valid because Carla is a single person
    - Some students constructed some kind of artificial discrete/countable population 
    - They frequently cited that her result could not represent a population **of other people**
- For example: 
    - "I would sample at least less then 10% of the overall population but not just one person." (Student 780)
    - "I would test a population of people on whether they have a good ear for music and then compare the students score compared to the rest of the population." (Student 1550)
- The intuition is reasonable to use a population to establish criterion for "a good ear", but this certainly does not disqualify use of inference


## Task Description: Rossman-Chance Task

Item credit: Rossman & Chance (2001)

### Prompt

An underlying principle of all statistical inference is that one uses sample statistics to learn something about the unknown population parameters. Demonstrate that you understand this statement by describing a realistic scenario in which you might use a sample statistic to infer something about a population parameter. For the context of your example, clearly identify:

-	the research question for your scenario,
-	the sample, 
-	the population, 
-	the statistic, and 
-	the parameter. 

Be as specific as possible, and do not use any example that was discussed in your statistics course.


## Selected responses to Rossman-Chance Task

- Student 1486: *Question:  Is facebook a popular social networking site among college students?  The **sample** will be 100 randomly selected students from 5 American campuses (500 students total).  The **population** will be college students.  The **statistic** will be whether or not they use facebook and the **parameter** will be yes or no.*

- Student 1550: *Is there a major difference in test scores of males verse females on their ACT scores? The **sample** is random sample of 500 juniors in [the state]. 250 males. 250 females. **Population**: all juniors in [the state]. **Statistic**: 500 **parameter**: all juniors in [the state].*

- Student 1459: *If you would like to figure out the average height of men aged from 20-35? /  Population: Everyone in that age range  /  Sample: selections made from the population  /  Statistic: The height from the men /  Parameter: The people who are getting tested*


## Observation: Lexical ambiguity/misconceptions of parameter

- Students showed a great deal of variability among concepts ascribed to key foundations of inferential statistics
- The task is unique in that it permits students to use a context of their own invention/choosing
- The **parameter** seemed particularly challenging for students, to which they ascribed a variety of concepts (e.g., a variable, a study constraint, a population).
- This is evidence of an issue 

## Task Description: Display Screen Quality

#### Key details

- An electronics company makes customized laptop computers for its customers by assembling various parts purchased in bulk from other companies. 
- The company purchases bulk orders of 150 display screens from a supplier.  
- If more than 5% of the display screens are bad, the company may reject the entire bulk order for a refund. 
- **A trained engineer [will] determine if each of the 150 display screens is good or bad before deciding whether to accept or reject the whole order.**  

#### Prompts

- Should statistical inference be used?  Explain. 

- Explain how you would decide whether the electronics company should accept or reject the order of display screens using the data gathered by the trained engineer.


## Selected responses to the Display Screens task

#. Student 719
    - *Inference?* "Yes, statistical inference should be used... we can find the margin of error and a confidence percentage that will lead us to accept or reject the bulk order. "
    - *Method?* "If 5% of the display screens from the supplier are bad, then that means 92.5 or more of them have to be good in order to accept them."

#. Student 122
    - *Inference?* "Statistical inference should be used because the sample is random every time."
    - *Method?* "You would have the trained engineer check each screen and if 8 or more of the screens were bad, send the order back."

## Observation: Discerning between deterministic and stochastic inquiry

- The pattern of self-contradiction is particularly of interest here.

- 32 of the 178 students ($\approx 18\%$) incorrectly claim statistical inference **IS** valid for the Display Screens task, BUT then described a **deterministic** solution.

- The converse was regularly observed in the note identification task.  Several students incorrectly claimed statistical inference was **NOT** valid, and then propose an **inferential** solution.


## Additional examples (deterministic/stochastic inquiry)

In the Note Identification task, a stochastic inquiry, we see the converse issue

#. Student 1541
    - *Inference?* "No statistical inference should not be used..."
    - *Method?* "You can use hypothesis testing to conclude a result. (1.) Determine the null and alternative hypothesis (2.) Find the p-value  (3.) Decide if the result is statistically significant (4.) Make a conclusion"

#. Student 1293
    - *Inference?* "Statistical inference should not be used to determine if Carla has a good ear for music or not because the sample size is too small and may not give any usable data."
    - *Method?* "The best way to decide if Carla has an ear for music would be to run a significance test with a confidence interval of 95%."


## Conclusions 
\small

1. Population as a process: 
    - finding: some students uncomfortable with a process as population
    - finding: some students unnecessarily imposed a more tangible population
    - illustrates a key challenge while "shuttling" from context to archetype described by Wild & Pfannkuch (1999)
2. Lexical ambiguity/misconceptions of parameter
    - finding: large variability of concepts ascribed to parameter
    - B. & delMas (in review) launched an extensive follow-up study of this issue and corroborated concurrent work of Kaplan & Rogness (2018).
    - evidence of difficulty "shuttling" from archetype to context described by Wild & Pfannkuch (1999)
3. Deterministic vs stochastic inquiry (i.e. Is this a statistical question?)
    - finding: students self-contradict... they advocate for one approach and then describe the opposite
    - evidence of difficulty discerning between deterministic and stochastic inquiry described by Franklin & Garfield (2006)


## What do you learn when you ask questions like this?

- We test our students' reflexes (Chance, 2002)
- Opportunities to distinguish between deterministic and stochastic inquiry
- Isolate each direction of "shuttling" as statistical thinking takes place
- Better insight into understanding & misconceptions of our students



<!---


Notes: 

- Presentation
    - don't present the paper
    - more "detail" than paper
    - share actual patterns of examples
- Time allocation (~ 20 mins?)
    - 5 min: Intro/background of study
    - 2 min on credibility of the instrument
    - 10 min show results
    - 3-5 min conclusion


"What is ISTUDIO designed to measure?"

- Discernment of statistical questions
    - this evaluation is the first step to productive analysis
    - W & P "PPDAC" cycle (P-P phase)
- Forward & backward transfer
    - W &P "shuttling"
    - assessment is designed to isolate each direction in the shuttling process
        - (BT) context to architype
        - (FT) architype to context

"What do you learn when you ask questions like this?"


Results/Issues to discuss
1. population as a process: 
    - summarize 2 examples
    - finding: some students constructed some kind of artificial discrete/countable population 
2. lexical ambiguity/misconceptions of parameter
    - summarize 2 examples
    - finding: large variability ascribed to parameter
    - finding: "study design detail/constraint" (cite ZDM & Kaplan papers)
3. is this a statistical question?
    - summarize 2 examples
    - finding: students self-contradict... say "no" and then use inference anyway

A new assessment tool called the Introductory Statistics Understanding and Discernment Outcomes (ISTUDIO) assessment tool was developed and administered to nearly 2000 students attending a wide variety of post-secondary institutions primarily in the United States. Students were observed to demonstrate measurable evidence of both forward-reaching and backward-reaching transfer outcomes. Unexpected response patterns revealed by the analysis of constructed response tasks are presented. Implications for teaching and research are discussed with attention toward both simulation-based and non-simulation-based introductory statistics curricula.

---> 
